--------------------------------------------------------
--  File created - Wednesday-September-07-2016   
--------------------------------------------------------
DROP TABLE "PROJECT"."CUSTOMER";
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"DOB" DATE, 
	"QUESTION1" VARCHAR2(200 BYTE), 
	"ANSWER1" VARCHAR2(200 BYTE), 
	"QUESTION2" VARCHAR2(200 BYTE), 
	"ANSWER2" VARCHAR2(200 BYTE), 
	"QUESTION3" VARCHAR2(200 BYTE), 
	"ANSWER3" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"CREATED_USER" VARCHAR2(200 BYTE), 
	"UPDATED_USER" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT.CUSTOMER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NEW_CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."NEW_CUSTOMER_PK" ON "PROJECT"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER" ADD CONSTRAINT "NEW_CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
