--------------------------------------------------------
--  File created - Wednesday-September-07-2016   
--------------------------------------------------------
DROP TABLE "PROJECT"."CUSTOMER_ADDRESS";
--------------------------------------------------------
--  DDL for Table CUSTOMER_ADDRESS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CUSTOMER_ADDRESS" 
   (	"ADDRESS_ID" NUMBER(38,0), 
	"STREET" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"ADDRESS_TYPE" VARCHAR2(200 BYTE), 
	"ACTIVE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT.CUSTOMER_ADDRESS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CUST_SHIPPING_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CUST_SHIPPING_ADDRESS_PK" ON "PROJECT"."CUSTOMER_ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_ADDRESS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CUST_SHIPPING_ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CUSTOMER_ADDRESS" MODIFY ("ZIP" NOT NULL ENABLE);
