--------------------------------------------------------
--  File created - Wednesday-September-07-2016   
--------------------------------------------------------
DROP TABLE "PROJECT"."SECURITY_QUESTIONS";
--------------------------------------------------------
--  DDL for Table SECURITY_QUESTIONS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."SECURITY_QUESTIONS" 
   (	"SECURITY_QID" NUMBER(38,0), 
	"SECURITY_QUESTIONS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT.SECURITY_QUESTIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CUST_SECURITY_QUESTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CUST_SECURITY_QUESTIONS_PK" ON "PROJECT"."SECURITY_QUESTIONS" ("SECURITY_QID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SECURITY_QUESTIONS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."SECURITY_QUESTIONS" MODIFY ("SECURITY_QID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."SECURITY_QUESTIONS" ADD CONSTRAINT "CUST_SECURITY_QUESTIONS_PK" PRIMARY KEY ("SECURITY_QID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
